{{- if .Values.httpRoute.enabled }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ include "privatize.fullname" . }}
  labels:
    {{- include "privatize.labels" . | nindent 4 }}
  {{- with .Values.httpRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  hostnames:
  {{- range .Values.httpRoute.hosts }}
  - {{ . }}
  {{- end }}
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: {{ .Values.httpRoute.gateway.name }}
    namespace: {{ .Values.httpRoute.gateway.namespace }}
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: {{ include "privatize.fullname" . }}
          port: {{ .Values.service.httpPort }}
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
{{- end }}